# Generated by Django 4.2.1 on 2023-05-20 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_adscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ads'),
        ),
    ]
